USE AssetDB;

ALTER TABLE assets
DROP FOREIGN KEY FK_Chk_EmployeeID;
ALTER TABLE assets
DROP FOREIGN KEY FK_Chk_AssetTypeID;
ALTER TABLE assets
DROP FOREIGN KEY FK_Chk_RoomNum;

DROP TABLE assettype;
DROP TABLE employee;
DROP TABLE assets;
DROP TABLE room;